name = input("what is your name? ")
age = input("how old are you? ")
department = input("what's your course of study in school? ")
print("my name is "+ name + ". I am " + age + " years old.")
print("I am a student of " + department)